apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - node-exporter-daemonset.yaml
  - kube-state-metrics.yaml
  - prometheus-rbac.yaml
  - prometheus-configmap.yaml
  - prometheus.yaml
  - grafana-datasource-configmap.yaml
  - grafana.yaml
